---
AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Register HealthChecks from the Biz-Ops API for Prometheus service discovery, runs on the existing ECS cluster.

Parameters:

  SplunkHecToken:
    Type: String
    Description: Find this at https://financialtimes.splunkcloud.com/en-GB/manager/financial_times_production/http-eventcollector.
    NoEcho: true

  DockerRevision:
    Type: String

  ServiceName:
    Type: String
    Default: "prometheus-biz-ops-service-discovery"

  ParentClusterStackName:
    Type: String
    Description: The parent CF stack which contains the ECS cluster definition.

  BizOpsApiKey:
    Type: String
    NoEcho: true

  ServiceHttpPort:
    Description: >
      The port to route http traffic from FT sources. Not exposed externally via ALB.
      See https://github.com/Financial-Times/monitoring-aggregation-ecs/blob/master/documentation/SERVICE_DEFINITIONS.md for guidelines
    Type: Number
    Default: 12006

Resources:

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      Volumes:
        - Name: efs-prometheus
          Host:
            SourcePath: /mnt/efs/prometheus
      ContainerDefinitions:
        - Name: !Sub "${ServiceName}-service"
          Image: !Sub "nexus.in.ft.com:5000/operations-reliability/${ServiceName}:${DockerRevision}"
          Environment:
            - Name: BIZ_OPS_API_KEY
              Value: !Ref BizOpsApiKey
            - Name: TICK
              Value: 60s
            - Name: DIRECTORY
              Value: /mnt/efs/prometheus/service-discovery
            - Name: PORT
              Value: !Ref ServiceHttpPort
          PortMappings:
            - ContainerPort: !Ref ServiceHttpPort
          DockerLabels:
            com.ft.service-name: !Sub "${ServiceName}-service"
            com.ft.service-region: !Ref "AWS::Region"
            com.prometheus-ecs-discovery.port: !Ref ServiceHttpPort
          MemoryReservation: 40 
          MountPoints:
            - ContainerPath: /mnt/efs/prometheus
              SourceVolume: efs-prometheus
          LogConfiguration:
            LogDriver: splunk
            Options:
              splunk-source: !Sub "${ServiceName}-${AWS::Region}.in.ft.com"
              splunk-url: https://http-inputs-financialtimes.splunkcloud.com
              splunk-token: !Ref SplunkHecToken
              splunk-format: json
              splunk-gzip: true
              tag: "{{.ImageName}}/{{.ImageID}}:{{.Name}}/{{.ID}}"
              labels: org.opencontainers.revision,org.opencontainers.created,com.ft.build-number,com.ft.service-name,com.ft.service-region

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue: !Sub "${ParentClusterStackName}-Name"
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
