---
AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Biz Ops Prometheus service discovery for Operations & Reliability, runs on the existing ECS cluster.

Parameters:

  SplunkHecToken:
    Type: String
    Description: Find this at https://financialtimes.splunkcloud.com/en-GB/manager/financial_times_production/http-eventcollector.
    NoEcho: true

  DockerRevision:
    Type: String
    Default: latest

  BizOpsApiKey:
    Type: String
    NoEcho: true

Resources:

  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Volumes:
        - Name: efs-prometheus
          Host:
            SourcePath: /mnt/efs/prometheus
      ContainerDefinitions:
        - Name: prometheus-biz-ops-service-discovery
          Image: !Sub "nexus.in.ft.com:5000/operations-reliability/prometheus-biz-ops-service-discovery:${DockerRevision}"
          MemoryReservation: 256
          MountPoints:
            - ContainerPath: /mnt/efs/prometheus
              SourceVolume: efs-prometheus
          Environment:
            - Name: BIZ_OPS_API_KEY
              Value: !Ref BizOpsApiKey
          Command:
            - --tick
            - 60s
            - --directory
            - /mnt/efs/prometheus/service-discovery
          LogConfiguration:
            LogDriver: splunk
            Options:
              splunk-source: !Ref AWS::StackName
              splunk-url: https://http-inputs-financialtimes.splunkcloud.com
              splunk-token: !Ref SplunkHecToken
              splunk-format: json
              splunk-gzip: true

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue "Prometheus-ECS-Cluster-Name"
      TaskDefinition: !Ref Task
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
